# Generated by Django 5.2.6 on 2026-04-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_remove_appsettings_meta_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='service_auto_print',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='service_paper_width_mm',
            field=models.PositiveIntegerField(default=58),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='service_printer_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='service_printer_type',
            field=models.CharField(blank=True, default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='service_receipt_footer',
            field=models.TextField(blank=True, default=''),
        ),
    ]
