# Generated by Django 5.2.6 on 2026-06-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_appsettings_service_auto_print_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='alegra_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
