# Generated by Django 5.2.6 on 2026-04-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_category_created_at_alter_product_created_at'),
        ('users', '0022_tenant_trial_end_date'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'active', '-created_at'], name='products_pr_tenant__1721d1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'category', 'active', '-created_at'], name='products_pr_tenant__1c388b_idx'),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(fields=['product', 'stock'], name='products_pr_product_390d48_idx'),
        ),
    ]
