# Generated by Django 5.2.6 on 2026-04-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_products_pr_tenant__1721d1_idx_and_more'),
        ('users', '0022_tenant_trial_end_date'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['tenant', 'active', 'position', '-created_at'], name='products_ca_tenant__cb0ff5_idx'),
        ),
    ]
