# Generated by Django 5.2.6 on 2026-04-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_category_products_ca_tenant__cb0ff5_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_stock',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
