# Generated by Django 5.2.6 on 2026-04-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_product_total_stock'),
        ('users', '0022_tenant_trial_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='stock',
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('tenant', 'sku'), name='unique_sku_per_tenant'),
        ),
    ]
