# Generated by Django 5.2.6 on 2026-06-19 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_purchase_purchaseitem_supplier_purchase_supplier'),
        ('users', '0024_userprofile_onboarding_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='purchases/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='products.purchase')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.tenant')),
            ],
        ),
    ]
