# Generated by Django 5.2.6 on 2026-04-23 04:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashsession',
            name='actual_balance',
        ),
        migrations.RemoveField(
            model_name='cashsession',
            name='expected_balance',
        ),
        migrations.RemoveField(
            model_name='cashsession',
            name='initial_balance',
        ),
        migrations.AddField(
            model_name='cashsession',
            name='actual_bank',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='cashsession',
            name='actual_cash',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='cashsession',
            name='expected_bank',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='cashsession',
            name='expected_cash',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='cashsession',
            name='initial_bank',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='cashsession',
            name='initial_cash',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
