# Generated by Django 5.2.6 on 2026-04-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='delivery_note',
            field=models.TextField(blank=True),
        ),
    ]
