# Generated by Django 5.2.6 on 2026-04-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_service_delivery_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='delivery_note',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
