# Generated by Django 5.2.6 on 2026-04-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0028_websiterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiterequest',
            name='proposals',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
