# Generated by Django 5.2.6 on 2026-04-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0029_websiterequest_proposals'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiterequest',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='files',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='questions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
