# Generated by Django 5.2.6 on 2026-04-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webconfig', '0030_websiterequest_answers_websiterequest_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiterequest',
            name='live_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
