# Generated by Django 5.2.6 on 2026-06-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_sale_apartado_amount_sale_apartado_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='dian_error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sale',
            name='dian_invoice_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='dian_invoice_status',
            field=models.CharField(choices=[('not_emitted', 'No Emitida'), ('emitted', 'Emitida'), ('error', 'Error')], default='not_emitted', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='dian_invoice_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
