# Generated by Django 5.2.6 on 2026-06-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_client_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='identification_type',
            field=models.CharField(blank=True, default='CC', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='tax_regime',
            field=models.CharField(blank=True, default='O-99', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
