# Generated by Django 5.2.6 on 2026-04-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_rename_ual_tenant_created_idx_users_tenan_tenant__e47f79_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
