# Generated by Django 5.2.6 on 2026-04-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_tenant_trial_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfiguration',
            name='enable_web_advertising',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantconfiguration',
            name='enable_web_sync',
            field=models.BooleanField(default=True),
        ),
    ]
